Sprint 06
RespectRus/MovieQuiz-ios pull request #10
Opened 2022-12-06 10:40 UTC by RespectRus

возникло предупреждение: "UIView.isHidden must be used from main thread only" в функции 
* private func loadingIndicator(isShown: Bool) {
        activityIndicator.isHidden = !isShown
        isShown ? activityIndicator.startAnimating() : activityIndicator.stopAnimating()
    } *

2022-12-07 10:56 UTC, ABashkirova requested changes

2022-12-07 10:56 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden. Эту настройку можно сделать один раз во viewDidLoad или на сториборде.

2022-12-07 10:56 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                        handler(.success(json))
👍🏻

2022-12-07 10:56 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
из-за удаления этой обертки, код начал выполняться не с главной очереди, поэтому ты видишь ворнинги фиолетовые в Xcode. Это ошибка, надо вернуть назад

2022-12-07 10:56 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        loadingIndicator(isShown: true)
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-12-07 12:28 UTC, RespectRus commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Исправил, спасибо!
 moviesLoader.loadMovies { [weak self] result in .... }  - нужно ли здесь делать слабую ссылку?

2022-12-07 12:44 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Я рекоменду ставить, хотя конкретно в этой реализации без ослабления ошибки не вызовет. 
это концептуальный вопрос: если не ставить, то надо помнить чтобы случайно не захватить сильно контекст.

2022-12-07 12:52 UTC, RespectRus commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Предыдущий ревьюер написал мне: "Вы уже захватили слабо self в кложуре метода loadMovies, ни к чему это делать снова при переводе задачи на главную очередь. 
* moviesLoader.loadMovies { [weak self] result in 
* DispatchQueue.main.async { [weak self] in  - " 
Видимо я не так понял его) Но если убрать слабую ссылку в переводе на главную очередь, выдает ошибку "Expected expression". Если честно, я немного запутался) подскажите пожалуйста)

2022-12-07 12:56 UTC, RespectRus commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
 Вот код из учебника)
func loadData() {
    moviesLoader.loadMovies { result in
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            switch result {
            case .success(let mostPopularMovies):
                self.movies = mostPopularMovies.items
                self.delegate.didLoadDataFromServer()
            case .failure(let error):
                self.delegate.didFailToLoadData(with: error)
            }
        }
    }
}

2022-12-07 13:00 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Тут похоже сыграло на вкус и цвет :) 

Тема ослабления ссылки не простая, разница в том где надо захватывать слабо, где надо еще раз переослаблять – зависит от того как код написан. 

В данном участке достаточно ослабить в первом замыкании, во втором уже нет необходимости. Однако не будет ошибочным код и когда первое замыкание захватывает неявно сильно контекст, а во внутреннем переослабляется. 

Важно следить, что во вложенном замыкании, ссылка ослаблена, если в предыдущем замыкании вы ее усилили через разыменовывание(например guard let self = self ), и в том, сохраняет ли замыкание вызываемый сервис. 

Так же  в замыканиях у DispatchQueue.main/UIView.animate тоже можно встретить, что разработчики не ослабляют self. Это может быть даже ок, зависит от контекста вызова. Один из комментариев Тимура как раз про этот случай. 

Я же всегда рекомендую оставлять [weak self] — это может быть неоптимальным решением, но точно не приведет к ошибке с ссылочным циклом. Вот когда есть понимание зачем ее не ослаблять (чуть ускорить приложение, оптимизация) – стоит расставлять ссылки по необходимости. Оптимизация не наш случай. 

Попробуйте эту статью (не легкая для первого раза, но через какое-то время перечитаете и будет проще):
https://habr.com/ru/company/otus/blog/666436/

2022-12-07 13:01 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Я боюсь, сильнее запутала только :)

2022-12-07 13:05 UTC, RespectRus commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Немного прояснилось. Обязательно прочитаю) Спасибо большое!

2022-12-07 13:09 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
Не могу сообразить с реализацией! Если я включу hidesWhenStopped в сториборде, мне надо кодом прописывать когда анимация должна быть, а когда нет? Или лучше все сразу писать кодом?

2022-12-07 13:11 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        loadingIndicator(isShown: true)
У меня индикатор не пропадает после получения ответа с сервера в течении первой игры)

2022-12-07 13:24 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
в сториборде параметры hidesWhenStopped и hidden;

* private func loadingIndicator() {
        activityIndicator.stopAnimating()
    }

2022-12-07 13:57 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
ой, а можно ссылку на учебник прям, кажется это надо поправить :( вероятно где-то забыли

2022-12-07 14:15 UTC, RespectRus commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
https://practicum.yandex.ru/learn/ios-developer/courses/be5032c4-b993-440d-8afe-f68940c9bbf9/sprints/75154/topics/d6c4890c-c58f-4781-9e48-249836ca0a84/lessons/e1b52991-2118-47e5-b29a-d4dbeeb2aef0/

" Доделываем мелочи" Авторское решение 2)

2022-12-07 14:22 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
Я правильно понимаю, реализация анимации загрузки с курса не верна?) 
Цитата предыдущего ревьюера)

"5. Методы showLoadingIndicator и hideLoadingIndicator можно объединить в один, передав туда параметр (isShown: Bool) * { 
* activityIndicator.isHidden = !isShown 
* isShown ? activityIndicator.startAnimating() : activityIndicator.stopAnimating() * } "

2022-12-07 15:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> -            DispatchQueue.main.async { [weak self] in
Спасибо большое, передам команде!

2022-12-09 13:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
> Не могу сообразить с реализацией! Если я включу hidesWhenStopped в сториборде, мне надо кодом прописывать когда анимация должна быть, а когда нет? 

если включишь на сториборде (или во вьюдидлоад, не имеет значения), то тебе свойство isHidden трогать больше не нужно будет. 

В коде останется только вызвать start/stop Animationg, то есть строчку 

> isShown ? activityIndicator.startAnimating() : activityIndicator.stopAnimating()

2022-12-09 13:01 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = !isShown
> Я правильно понимаю, реализация анимации загрузки с курса не верна?)

Почему неверна? верна :) Просто Тимур предложил как еще можно сделать :) на его взгляд этот код будет лучше. Мне тоже нравится. 

Надо понимать, что у всех разработчиков разный опыт, вкус на код. И не все рекомендации попадают под черно-белое правильно/неправильно.

2022-12-10 19:13 UTC, ABashkirova approved these changes
Можно слить

2022-12-12 08:09 UTC, RespectRus commented
1

2022-12-12 08:27 UTC, merged