sprint_07
RespectRus/MovieQuiz-ios pull request #13
Opened 2022-12-14 13:31 UTC by RespectRus

2022-12-18 10:35 UTC, ABashkirova approved these changes

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITests.swift
> +    private func tapButtonNo() {
не очень конкретное название, по нему не ожидаешь, что будет выполнено 10 нажатий

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +         XCTAssertNotNil(viewModel.image)
Control + i чтобы поправить форматриование
```suggestion
        XCTAssertNotNil(viewModel.image)
```

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuiz/Services/NetworkClient.swift
> +                response.statusCode < 200 && response.statusCode >= 300 {
А почему условие поменялось?

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let alert = UIAlertController(
а почему контроллер создает UIAlertController? Можно же алерт-презентер для этих целей использовать

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            if self.isLastQuestion() {
форматриование поехало, давай выделим класс и зажмем control+i

2022-12-18 10:35 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            if self.isLastQuestion() {
self можно опускать вне замыканий
```suggestion
            if isLastQuestion() {
```

2022-12-18 10:38 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITests.swift
> +    }
Тесты падают, так как метка "Alert" выставлена не тому UIAlertPresenter'у

2022-12-18 10:39 UTC, ABashkirova requested changes
Приношу извинения, работу приняла на платформе по ошибке:

нужно дополнительно поправить UI тесты

2022-12-19 08:36 UTC, RespectRus commented on MovieQuiz/Services/NetworkClient.swift
> +                response.statusCode < 200 && response.statusCode >= 300 {
В учебнике было в примере, поменял обратно)

2022-12-19 08:40 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let alert = UIAlertController(
Так сделано в учебнике)

2022-12-19 08:41 UTC, RespectRus commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            if self.isLastQuestion() {
исправил

2022-12-19 08:47 UTC, merged